#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         3
#bspc config border_radius        10
bspc config top_padding         30
bspc config bottom_padding      35
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color          "#0F1419"
bspc config focused_border_color         "#00364D"

# ----------> AutoStart <---------

picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/.config/backgrounds/BG-4.jpg &
sh ~/.config/scripts/autostart.sh &
sh ~/.config/polybar/launch.sh &
mocp &
